version: '3.9'

services:

  mongo:
    image: mongo:6.0.3
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: senteventlist
      MONGO_INITDB_USERNAME: user
      MONGO_INITDB_PASSWORD: user
    command: mongod --auth
    volumes:
      - mongodb_data_container:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: user
      ME_CONFIG_MONGODB_URL: mongodb://user:user@mongo:27017/

volumes:
  mongodb_data_container:
    driver: local
